import Head from "next/head";
import React from "react";
import Header from "../components/Header";

const Layout = ({ children, titlePage }) => {
  return (
    <div>
      <Head>
        <title>Sitio de Guitarraa - {titlePage}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      {children}
    </div>
  );
};

export default Layout;
